### ISSUE TITLE
css error signup form

### ISSUE THREAD

**Issue by x0rld** [manikandanraji/youtubeclone-frontend#12]
I'm on firefox 68, when I click to signup there is this 
![image](https://user-images.githubusercontent.com/45242856/87905968-005e3080-ca62-11ea-8e20-0a7910b4bca7.png)

**Comment by manikandanraji** [comment]
![fixed](https://user-images.githubusercontent.com/34580944/87929125-8e0e4000-caa3-11ea-9e1f-9c76c6c0e3e4.png)

Fixed now
