### ISSUE TITLE
where to find buildpacks use in frontend for heroku deploy

### ISSUE THREAD

**Issue by hostitor** [manikandanraji/youtubeclone-frontend#13]
hi manikandanraji , 
where to find buildpacks use in frontend for heroku deploy
I'm deployed backend at : https://youtubeclone-backend.herokuapp.com/
& front end here : https://youtubeclone-frontend.herokuapp.com/
my .env values for frond end is :
REACT_APP_BACKEND_URL : https://youtubeclone-backend.herokuapp.com/
REACT_APP_CLOUDINARY_ENDPOINT : https://api.cloudinary.com/v1_1/aparat
after run consule in bash & after two command npm i & npm start , my frontend dyno run in application error
my dyno log :
https://gist.github.com/hostitor/9114f7e721c73437fa40409bc107c79b
waiting for your response
regards , mohamad

edit : I also build frontend on netlify on : https://darktube.netlify.app/
but can't be register account

**Comment by manikandanraji** [comment]
In the backend, you need to setup these following .env at the root of the project:

```javascript
JWT_SECRET=[X]
JWT_EXPIRE=[X] // eg: 30d
DATABASE_URL=[X]
```

For the 'DATABASE_URL' you can use heroku postgress addon. When you add this addon, heroku will automatically setup the .env for DATABASE_URL 

You can use the heroku dasboard to add this addon. Go to heroku and open your backend app, in the 'Resources tab' you can search for 'Heroku Postgres' and choose the plan, 'hobby dev' plan is free.

![help](https://user-images.githubusercontent.com/34580944/89098528-27bfe080-d406-11ea-8069-f4c2ed35653a.png)

**Comment by hostitor** [comment]
hello again manikandanraji,
i set done heroku env variables below :
https://i.imgur.com/7FKfCK7.png
but not work on frontend 
please help me to resolve it
waiting for your response 
finest regards

**Comment by manikandanraji** [comment]
In your frontend that you have deployed at netlify, change the env var for 'REACT_APP_BACKEND_URL' to the following:

REACT_APP_BACKEND_URL=https://youtubeclone-backend.herokuapp.com/api/v1/

To upload images and videos without using cloudinary API key, you need to set an 'upload preset'. Here's how you would do that:

1. Once you created an account, go to 'https://cloudinary.com/console'
2. Click the settings icon at the top right, there you will see four tabs, click the upload tab.
3. In upload tab area, you will see a link 'Add Upload preset', click that.
4. Once you navigated to upload preset page, you need to set these options:
	- set 'upload preset name' to 'youtubeclone'
	- choose 'signining mode' to 'Unsigned'
	- [optional] you can also specify the folder to upload videos and images
5. Hit 'save'

**Comment by hostitor** [comment]
bro , i go step by step exactly your rules but can't be register on frontend
please help
